// <auto-generated />
using ARTICULOS_API.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ARTICULOS_API.Migrations
{
    [DbContext(typeof(ArticulosDBContext))]
    [Migration("20221009210532_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("ARTICULOS_API.Entities.Articulos", b =>
                {
                    b.Property<int>("ArticuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Existencia")
                        .HasColumnType("REAL");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ArticuloId");

                    b.ToTable("Articulos");

                    b.HasData(
                        new
                        {
                            ArticuloId = 1,
                            Descripcion = "Smart Phone",
                            Existencia = 10.0,
                            Marca = "Samsung"
                        },
                        new
                        {
                            ArticuloId = 2,
                            Descripcion = "Smart TV",
                            Existencia = 5.0,
                            Marca = "Samsung"
                        },
                        new
                        {
                            ArticuloId = 3,
                            Descripcion = "iPhone 14",
                            Existencia = 10.0,
                            Marca = "Apple"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
